# Generated by Django 4.2.2 on 2023-07-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangastore', '0005_alter_carrito_cliente_alter_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default='Some', null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='some'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
