# Generated by Django 4.2.2 on 2023-07-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangastore', '0006_producto_available_producto_image_producto_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default='Some', null=True, upload_to='media/'),
        ),
    ]
