# Generated by Django 4.2.2 on 2023-07-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangastore', '0007_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='Some', null=True, upload_to='mangas'),
        ),
    ]
