# Generated by Django 4.2.2 on 2023-07-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangastore', '0009_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
